//
// Created by marco on 16/12/2020.
//

#ifndef DICOTOMIATESSUTI_ERRORI_H
#define DICOTOMIATESSUTI_ERRORI_H

#define NOME_CHIAVE_NULLO 199
#define TESTO_DOMANDA_NULLO 200
#define AGGIUNTA_CHIAVE_NULLA 201
#define AGGIUNTA_VERSO_CHIAVE_NULLA 202
#define ERRORE_CREAZIONE_SOTTOTIPI 203
#define ERRORE_CREAZIONE_CHIAVE 204
#define ERRORE_RAGGRUPPAMENTO 205
#define SOTTOTIPI_NON_NULLI 206
#define ERRORE_INSERIMENTO 207
#define ERRORE_CREAZIONE_DOMANDA 208
#define DOMANDA_NULLA 209
#define CHIAVE_NULLA 210

#endif //DICOTOMIATESSUTI_ERRORI_H
